galaxy_uid: 10010
galaxy_gid: 10010

use_internal_ips: true

# cloud-init template for /etc/hosts
hosts_template_file: "/etc/cloud/templates/hosts.debian.tmpl"

influx_url: stats.usegalaxy.org.au
grafana_server_url: "https://{{ influx_url }}:8086"

# Monitoring
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{ grafana_server_url }}"]
      - database = "aarnet"
      - precision = "s"
      - username = "node"
      - password = "{{ vault_influx_node_password }}"