slurm_roles: ['exec']

add_hosts_head: yes
add_hosts_galaxy: yes

attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4

shared_mounts:
    - path: /mnt/galaxy
      src: aarnet-dev:/mnt/galaxy
      fstype: nfs
      state: mounted

# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs

# Interactive Tools
docker_install_compose: false
docker_users:
  - "{{ galaxy_user.name }}"