# append domain to ansible_hostname (from hosts file) for hostname variable
hostname: "{{ ansible_hostname }}.usegalaxy.org.au"
iksjdhfkshdfjhsdkjfhsk
#List of users to install and setup /homes for
machine_users:
    - name: simon
      role: sudo
      key: files/keys/simon.pub
      email: "{{ simon_email }}"
    - name: nick
      role: sudo
      key: files/keys/nick.pub
      email: "{{ nick_email }}"
    - name: cat
      role: sudo
      key: files/keys/catherine.pub
      email: "{{ cat_email }}"
    - name: thom
      role: sudo
      key: files/keys/thom.pub
      email: "{{ thom_email }}"
    - name: igor
      role: user
      key: files/keys/igor.pub
      email: "{{ igor_email }}"
    - name: mike
      role: user
      key: files/keys/mike.pub
      email: "{{ mike_email }}"
    - name: gareth
      role: user
      key: files/keys/gareth.pub
      email: "{{ gareth_email }}"
    - name: jenkins_bot
      role: sudo
      key: files/keys/jenkins_bot.pub
      email: "{{ jenkins_bot_email }}" # this is not a real email address and will cause issues if validation is required

galaxy_user:
  name: galaxy
  shell: /bin/bash
  uid: "{{ galaxy_uid }}"
  group: galaxy
  gid: "{{ galaxy_gid }}"

#Common packages to install on all of our machines.
common_packages:
    - python-is-python3
    - vim
    - acl
    - git
    - build-essential
    - python3-dev
    - libcurl4-openssl-dev
    - libgnutls28-dev
    - libssl-dev
    - python3-virtualenv
    - python3-pip
    - htop
    - nfs-common
    - atop
    - speedometer
    - byobu
    - apt-transport-https
    - tar
    - bzip2
    - libgl1-mesa-glx 

#Set pip to be pip3 by default - see roles/geerlingguy.pip/defaults/main.yml
pip_package: python3-pip

# cvmfs
cvmfs_role: client
galaxy_cvmfs_repos_enabled: true

