# append domain to ansible_hostname (from hosts file) for hostname variable
hostname: "{{ ansible_hostname }}.genome.edu.au"  # cat-dev branch has this domain

head_nodes: "{{ groups['dev_slurm_head'] }}"
worker_nodes: "{{ groups['dev_workers'] }}"
galaxy_nodes: "{{ groups['dev_galaxy_server'] }}"

#List of users to install and setup /homes for
machine_users:
    - name: simon
      role: sudo
      key: files/keys/simon.pub
    - name: nick
      role: sudo
      key: files/keys/nick.pub
    - name: cat
      role: sudo
      key: files/keys/catherine.pub
    - name: igor
      role: user
      key: files/keys/igor.pub
    - name: thom
      role: sudo
      key: files/keys/thom.pub
    - name: mike
      role: user
      key: files/keys/mike.pub
    - name: gareth
      role: user
      key: files/keys/gareth.pub

galaxy_user:
  name: galaxy
  shell: /bin/bash
  uid: 998
  group: galaxy
  gid: 998

#Common packages to install on all of our machines.
common_packages:
    - python-is-python3
    - vim
    - acl
    - git
    - build-essential
    - python3-dev
    - libcurl4-openssl-dev
    - libssl-dev
    - python3-virtualenv
    - python3-pip
    - htop
    - nfs-common
    - atop
    - speedometer
    - byobu
    - apt-transport-https
    - tar
    - bzip2

#Set pip to be pip3 by default - see roles/geerlingguy.pip/defaults/main.yml
pip_package: python3-pip
