postgresql_objects_users:
  - name: galaxy
    password: "{{ galaxy_db_user_password }}"
    db: galaxy
    priv: "ALL"
  - name: reader
    password: "{{ galaxy_db_reader_password }}"
    db: galaxy
  - name: tiaasadmin
    password: "{{ galaxy_db_tiaasadmin_password }}"
    db: galaxy
  - name: tiaas
    password: "{{ galaxy_db_tiaas_password }}"
    db: galaxy

# *********** Can't be run until after Galaxy is setup and installed *******************
postgresql_objects_privileges:
  - database: galaxy
    roles: reader,tiaasadmin
    objs: ALL_IN_SCHEMA
    privs: SELECT
  - database: galaxy
    roles: tiaasadmin
    objs: group_role_association,user_group_association,user_role_association,role,galaxy_group
    privs: DELETE
  - database: galaxy
    roles: tiaas
    objs: galaxy_user,galaxy_session,job
    type: table
    privs: SELECT
  - database: galaxy
    roles: tiaas
    objs: user_group_association,galaxy_group,role,group_role_association
    type: table
    privs: SELECT,INSERT
  - database: galaxy
    roles: tiaas
    objs: role_id_seq,galaxy_group_id_seq,group_role_association_id_seq,user_group_association_id_seq
    type: sequence
    privs: USAGE,SELECT
  - database: galaxy
    roles: tiaas
    objs: group_role_association
    type: table
    privs: DELETE
# ***********
postgresql_objects_databases:
  - name: galaxy
    owner: galaxy
