galaxy_job_metrics_plugins:
- type: core
- type: cpuinfo
- type: meminfo
- type: env
  variables: 'HOSTNAME,SLURM_CPUS_ON_NODE,SLURM_JOB_ID'

pulsar_job_metrics_plugins: "{{ galaxy_job_metrics_plugins }}"
