# Certbot
certbot_virtualenv_package_name: python3-virtualenv

certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auth_method: --webroot
certbot_install_method: virtualenv
certbot_auto_renew: yes
certbot_auto_renew_user: root
certbot_environment: production
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx
  - rabbitmq
certbot_post_renewal: |
    systemctl restart nginx || true
    systemctl restart rabbitmq-server || true
certbot_domains:
 - "{{ hostname }}"
certbot_agree_tos: --agree-tos

# NGINX
nginx_selinux_allow_local_connections: true
nginx_servers:
  - redirect-ssl
nginx_enable_default_server: false
nginx_ssl_servers:
  - rabbitmq
nginx_conf_http:
  client_max_body_size: 1g
nginx_remove_default_vhost: true

# NGINX Letsencrypt bindings
nginx_ssl_role: usegalaxy_eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem

#telegraf extra stuff
#telegraf_plugins_extra:
#    rabbitmq:
#    plugin: rabbitmq
#    config:
#      - url = "http://localhost:15671"
#      - username = "telegraf"
#      - password = "{{ rabbitmq_password_telegraf }}"

# Common RabbitMQ settings

rabbitmq_plugins:
  - rabbitmq_management

rabbitmq_config:
- rabbit:
  - ssl_listeners:
    - "'0.0.0.0'": 5671
    - "'127.0.0.1'": 5671
  - ssl_options:
    - cacertfile: /etc/ssl/certs/fullchain.pem
    - certfile: /etc/ssl/certs/cert.pem
    - keyfile: /etc/ssl/user/privkey-rabbitmq.pem
    - fail_if_no_peer_cert: 'false'
#- rabbitmq_management:
#  - listener:
#    - port: 15671
#    - ssl: true
#    - ssl_opts:
#      - cacertfile: /etc/ssl/certs/fullchain.pem
#      - certfile: /etc/ssl/certs/cert.pem
#      - keyfile: /etc/ssl/user/privkey-rabbitmq.pem
#      - verify: verify_none
#      - fail_if_no_peer_cert: false
