- hosts: aarnet-job-nfs
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/aarnet.yml
      - group_vars/VAULT
      - group_vars/nfs_servers.yml
      - host_vars/aarnet-job-nfs.usegalaxy.org.au.yml
  pre_tasks:
      - name: Attach volume to instance
        include_role:
          name: attached-volumes
      - name: Create galaxy_job_dir directory
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - "{{ galaxy_job_dir }}"
          - "{{ galaxy_job_dir }}/user-data-test"  # Temporary path for testing
  roles:
      - common
      - insspb.hostname
      - geerlingguy.pip
      - geerlingguy.nfs
      - dj-wasabi.telegraf
  post_tasks:
      - name: Chown shared dirs to Galaxy user
        file:
          path: "{{ item }}"
          owner: galaxy
          group: galaxy
        with_items:
          - "{{ galaxy_job_dir }}"
          - "{{ galaxy_job_dir }}/user-data-test"  # Temporary path for testing
      - name: Reload exportfs
        command: exportfs -ra
        become: yes
        become_user: root
        
