- hosts: aarnet_dev_workers
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/aarnet-dev.yml
      - group_vars/VAULT
      - group_vars/aarnet-dev-slurm.yml
      - group_vars/aarnet-dev_workers.yml
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  roles:
      - common
      - insspb.hostname
      - geerlingguy.pip
      - mounts
      - galaxyproject.repos
      - galaxyproject.slurm
      - galaxyproject.cvmfs
      - dj-wasabi.telegraf
      - geerlingguy.docker
  post_tasks:
      - name: restart munge
        systemd:
            name: munge
            state: restarted
      - name: Move /tmp to mounted disk
        block:
          - name: Create worker tmpdir on mounted disk
            file:
                path: /mnt/tmpdisk
                state: directory
                owner: root
                group: root
                mode: '1777'
          - name: stat links
            stat:
                path: /tmp
            register: links
          - name: remove old tmp
            file:
                path: /tmp
                state: absent
            when: links.stat.islnk is defined and not links.stat.islnk
          - name: Link /tmp to /mnt/tmpdisk
            file:
                src: /mnt/tmpdisk
                dest: /tmp
                state: link
            become: yes
            become_user: root
            when: links.stat.islnk is defined and not links.stat.islnk
        when: attached_volumes is defined
