- hosts: aarnet_dev_db_server
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/aarnet-dev.yml
      - group_vars/VAULT
      - group_vars/dbservers.yml
      - host_vars/aarnet-dev-db.usegalaxy.org.au.yml
  pre_tasks:
      - name: Attach volume to instance
        include_role:
          name: attached-volumes
      - name: Install psycopg2 for python3
        apt:
            name: python3-psycopg2
            state: present
        become: true
      - name: create data directory
        file:
          path: /data/production
          owner: postgres
          group: postgres
          state: directory
          mode: 0700
  roles:
      - common
      - insspb.hostname
      - geerlingguy.pip
      - galaxyproject.postgresql
      - role: natefoo.postgresql_objects
        become: true
        become_user: postgres
      - dj-wasabi.telegraf
