- hosts: dev-pulsar
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/dev.yml
    - group_vars/pulsarservers.yml
    - group_vars/dev_pulsar_slurm.yml
    - group_vars/VAULT
    - host_vars/dev-pulsar.usegalaxy.org.au.yml
  vars:
    special_pulsar_message_queue_url: "pyamqp://galaxy_au:{{ vault_rabbitmq_password_galaxy_au_aarnet_dev }}@aarnet-dev-queue.usegalaxy.org.au:5671//pulsar/galaxy_au?ssl=1"
  pre_tasks:
    - name: apt update
      apt:
        cache_valid_time: 3600
        update_cache: yes
      when: ansible_os_family == "Debian"
  roles:
    - common
    - insspb.hostname
    - geerlingguy.pip
    - galaxyproject.repos
    - galaxyproject.pulsar
    - geerlingguy.nfs
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - pulsar-post-tasks
