- hosts: dev_galaxy_server
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/dev.yml
      - group_vars/VAULT
      - group_vars/galaxyservers.yml
      - group_vars/dev_slurm.yml
      - host_vars/dev.usegalaxy.org.au.yml
  pre_tasks:
      - name: Attach main volume to instance
        include_role:
          name: set-up-volume
        vars:
          attached_volume_device: "{{ galaxyserver_attached_volume_device }}"
          attached_volume_fstype: "{{ galaxyserver_attached_volume_fstype }}"
          attached_volume_path: "{{ galaxyserver_attached_volume_path }}"
      # - name: Attach upload store volume to instance
      #   include_role:
      #     name: set-up-volume
      #   vars:
      #     attached_volume_device: "{{ uploadstore_attached_volume_device }}"
      #     attached_volume_fstype: "{{ uploadstore_attached_volume_fstype }}"
      #     attached_volume_path: "{{ uploadstore_attached_volume_path }}"
      - name: Ensure that upload_store directories exist
        file:
            path: "{{ item }}"
            state: directory
            mode: '755'
        with_items:
          - "{{ nginx_upload_store_dir }}"
          - "{{ nginx_upload_job_files_store_dir }}"
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.repos
    - common
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - usegalaxy_eu.galaxy_systemd
    - nginx-with-dynamic-module
    - galaxyproject.nginx
    - geerlingguy.nfs
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - usegalaxy_eu.gxadmin
    - pg-post-tasks
    - usegalaxy_eu.tiaas2
  post_tasks:
    - name: Clone Galaxy-Owncloud-Integration
      git:
        repo: https://github.com/usegalaxy-au/Galaxy-Owncloud-Integration
        dest: "{{ galaxy_server_dir }}/tools/Galaxy-Owncloud-Integration"
        update: no
      when: use_cloudstor_conf|d(false) == true
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
    - name: Reload exportfs
      command: exportfs -ra
      become: yes
      become_user: root

