- hosts: galaxy, galaxy-queue, galaxy_workers
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/galaxy_etca.yml
    - group_vars/VAULT
    - group_vars/galaxyservers.yml
    - group_vars/galaxy_etca_slurm.yml
    - host_vars/galaxy.usegalaxy.org.au.yml
    - secret_group_vars/stats_server_vault
  handlers:
    - name: Restart Slurmd
      systemd:
        name: slurmd
        state: restarted
    - name: Restart Slurmctld
      systemd:
        name: slurmctld
        state: restarted
  roles:
    - galaxyproject.slurm