- hosts: galaxy_slurm_head
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/galaxy_etca.yml
      #   - group_vars/rabbitservers.yml  # put rabbitmq vars in host_vars file
      - group_vars/VAULT
      - host_vars/galaxy-queue.usegalaxy.org.au.yml
      - group_vars/galaxy_etca_slurm.yml
      - secret_group_vars/stats_server_vault
  roles:
      - common
      - insspb.hostname
      - geerlingguy.pip
      - jasonroyle.rabbitmq
      - galaxyproject.nginx
      - mariadb
      - galaxyproject.repos
      - galaxyproject.slurm
      # - dj-wasabi.telegraf
      - slurm-post-tasks