- hosts: pawsey-job-nfs
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/pawsey.yml
      - group_vars/VAULT
      - group_vars/nfs_servers.yml
      - host_vars/pawsey-job-nfs.usegalaxy.org.au.yml
      - secret_group_vars/ubuntu_maintenance_key
  pre_tasks:
      - name: Attach volume to instance
        include_role:
          name: attached-volumes
      - name: Create galaxy_job_dir directory
        file:
          path: "{{ galaxy_job_dir }}"
          state: directory
  roles:
      - common
      - insspb.hostname
      - geerlingguy.pip
      - geerlingguy.nfs
  post_tasks:
      - name: Chown shared dirs to Galaxy user
        file:
          path: "{{ galaxy_job_dir }}"
          owner: galaxy
          group: galaxy
      - name: Reload exportfs
        command: exportfs -ra
        become: yes
        become_user: root
        
