- hosts: pawsey-backup
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/pawsey.yml
      - group_vars/VAULT
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  roles:
    - galaxyproject.repos
    - common
    - geerlingguy.pip
    - slg.db-backup
    - dj-wasabi.telegraf
