- name: Pulsar NCI training worker node install
  hosts: pulsar_nci_training_workers
  become: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training_workers.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training_slurm.yml
    - group_vars/VAULT
    - secret_group_vars/stats_server_vault
  pre_tasks:
    - name: Remove cloudinit entry in fstab
      # remove line '/dev/vdb	/mnt	auto	defaults,nofail,x-systemd.requires=cloud-init.service,comment=cloudconfig	0	2'
      # because this is the same mount point as the one we need for the attached volume + pulsar nfs mount
      lineinfile:
        path: /etc/fstab
        regexp: "\/dev\/vdb\\s+\/mnt.*"
        state: absent
    - name: Create worker extra disk mount point on /mnt
      file:
          path: /mnt/tmpdisk
          state: directory
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  roles:
      - common
      - insspb.hostname
      - galaxyproject.legacy_slurm
      - mounts
      - galaxyproject.repos
      - galaxyproject.cvmfs
      - gantsign.golang
      - cyverse-ansible.singularity
      - geerlingguy.docker
      - acl-on-startup
      - dj-wasabi.telegraf
  post_tasks:
      - name: Restart munge service
        service:
            name: munge
            state: restarted
      - name: Move /tmp to vdb
        block:
          - name: Create worker tmpdir on /mnt
            file:
                path: /mnt/tmpdisk
                state: directory
                owner: root
                group: root
                mode: '1777'
          - name: stat links
            stat:
                path: /tmp
            register: links
          - name: remove old tmp
            file:
                path: /tmp
                state: absent
            when: links.stat.islnk is defined and not links.stat.islnk
          - name: Link /tmp to /mnt/tmpdisk
            file:
                src: /mnt/tmpdisk
                dest: /tmp
                state: link
            become: yes
            become_user: root
            when: links.stat.islnk is defined and not links.stat.islnk
        when: attached_volumes is defined
