- name: Pulsar NCI Training Head Node
  hosts: pulsar_nci_training_head
  become: true
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
    - name: Remove cloudinit entry in fstab.
      # Remove line '/dev/vdb	/mnt	auto	defaults,nofail,x-systemd.requires=cloud-init.service,comment=cloudconfig	0	2'
      # because this is the same mount point as the one we need for the attached volume + pulsar nfs mount
      lineinfile:
        path: /etc/fstab
        regexp: "\/dev\/vdb\\s+\/mnt.*"
        state: absent
    - name: Create pulsar deps path
      file:
        path: "{{ pulsar_dependencies_dir }}"
        state: directory
        owner: "{{ pulsar_user.name }}"
        group: "{{ pulsar_user.name }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training_slurm.yml
    - group_vars/VAULT
    - host_vars/pulsar-nci-training/pulsar-nci-training.usegalaxy.org.au.yml
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ubuntu_maintenance_key
  roles:
    - common
    - insspb.hostname
    - geerlingguy.pip
    - galaxyproject.repos
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ pulsar_user.name }}"
    - galaxyproject.pulsar
    - geerlingguy.nfs
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - gantsign.golang
    - cyverse-ansible.singularity
    - geerlingguy.docker
    - acl-on-startup
    - dj-wasabi.telegraf
    - pulsar-post-tasks
    - slurm-post-tasks
    # - slg.galaxy_stats
  post_tasks:
    - name: Reload exportfs
      command: exportfs -ra
