- hosts: staging_galaxy_server
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/staging.yml
      - group_vars/VAULT
      - group_vars/galaxyservers.yml
      - group_vars/staging_slurm.yml
      - host_vars/staging.usegalaxy.org.au.yml
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.repos
    - common
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.galaxy
    - usegalaxy_eu.galaxy_systemd
    - nginx-upload-module
    - galaxyproject.nginx
    - geerlingguy.nfs
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - usegalaxy_eu.gxadmin
    - pg-post-tasks
  post_tasks:
    - name: Clone Galaxy-Owncloud-Integration
      git:
        repo: https://github.com/usegalaxy-au/Galaxy-Owncloud-Integration
        dest: "{{ galaxy_server_dir }}/tools/Galaxy-Owncloud-Integration"
        update: no
      when: use_cloudstor_conf|d(false) == true
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
    - name: Reload exportfs
      command: exportfs -ra
      become: yes
      become_user: root
