- hosts: galaxy_group
  become: true
  tasks:
    - name: add galaxy australia authorised key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', 'files/keys/galaxy-australia.pub') }}"