hostname: "{{ ansible_hostname }}.genome.edu.au"

# Keys and shares

create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "Vic"
ssl_location: "Melbourne"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Pulsar Mel3"
ssl_email: "help@genome.edu.au"

#host specific pulsar settings

rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_mel3_pawsey }}"
pulsar_queue_url: "pawsey-queue.usegalaxy.org.au"
pulsar_rabbit_username: "galaxy_mel3"
pulsar_rabbit_vhost: "/pulsar/galaxy_mel3"

#Attached volume
attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
