# tpv config file for aarnet testing

global:
  default_inherits: default

tools:
  default:
    cores: 1
    mem: cores * 3.8
    env: {}
    params:
      nativeSpecification: "--nodes=1 --ntasks={cores} --ntasks-per-node={cores} --mem={round(mem*1024)}"
      submit_native_specification: "--nodes=1 --ntasks={cores} --ntasks-per-node={cores} --mem={round(mem*1024)}"
    scheduling:
      reject:
        - offline
    rules: []
    rank: |
      helpers.weighted_random_sampling(candidate_destinations)

destinations:
  slurm:
    cores: 32
    mem: 121.25
    scheduling:
      accept:
      - slurm
      - training
  pulsar-paw:
    cores: 8
    mem: 31.36
    scheduling:
      require:
      - pulsar-paw
      - pulsar
  pulsar-nci-test:
    cores: 16
    mem: 48.19
    scheduling:
      accept:
        - general
        - pulsar-nci-test
      require:
        - pulsar

users:
  jenkins_bot@usegalaxy.org.au:
    cores: 1
    mem: cores * 3.8
    params:
      nativeSpecification: "--nodes=1 --ntasks={cores} --ntasks-per-node={cores} --mem={round(mem*1024)} --partition=main"
    scheduling:
      require:
        - slurm
  pulsar_paw_user@usegalaxy.org.au:
    rules:
      - match: tool.id.startswith('toolshed') or tool.id.startswith('testtoolshed')
        scheduling:
          accept:
            - pulsar
            - offline
          require:
            - pulsar-paw
  pulsar_nci_test_user@usegalaxy.org.au:
    rules:
      - match: tool.id.startswith('toolshed') or tool.id.startswith('testtoolshed')
        scheduling:
          require:
            - pulsar
            - pulsar-nci-test