- hosts: pulsar_QLD_head
  become: true
  become_user: ubuntu
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/pulsarservers.yml
    - ../../group_vars/pulsar_QLD/pulsar-QLD.yml
    - ../../host_vars/pulsar-QLD/pulsar-QLD.genome.edu.au.yml
    - conda_environments.yml
  tasks:
    - name: Create and update conda envs
      include_tasks: conda_create_update.yml