- hosts: pulsar_mel3_head
  become: true
  become_user: ubuntu
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/pulsarservers.yml
    - ../../group_vars/pulsar-mel3.yml
    - ../../host_vars/pulsar-mel3/pulsar-mel3.genome.edu.au
    - conda_environments.yml
  tasks:
    - name: Create and update conda envs
      include_tasks: conda_create_update.yml