- hosts: pulsar_nci_test_head
  become: true
  become_user: ubuntu
  vars_files:
    - ../../group_vars/all.yml
    - ../../group_vars/pulsarservers.yml
    - ../../group_vars/pulsar-nci-test/pulsar-nci-test.yml
    - ../../host_vars/pulsar-nci-test/pulsar-nci-test.usegalaxy.org.au.yml
    - conda_environments.yml
  tasks:
    - name: Create and update conda envs
      include_tasks: conda_create_update.yml