---
- name: Create stats files and cron jobs for stats collection user
  become: yes
  become_user: "{{ stats_collection_user }}"
  block:
  # Common stuff
  - name: Create stats dir
    file:
      path: "{{ stats_dir }}"
      state: directory

  - name: Copy requirements file
    copy:
      src: files/requirements.txt
      dest: "{{ stats_dir }}/requirements.txt"
      mode: 0755

  - name: Create virtualenv
    pip:
      virtualenv: "{{ virtualenv_dir }}"
      requirements: "{{ stats_dir }}/requirements.txt"

  # sinfo info :)
  - name: copy get_queue_size.py
    template:
      src: templates/get_queue_size.py.j2
      dest: "{{ stats_dir}}/get_queue_size.py"
      mode: 0755
    when: add_utilisation_info or add_queue_info

  - name: copy current_stats
    template:
      src: templates/current_stats.sh.j2
      dest: "{{ stats_dir }}/current_stats.sh"
      mode: 0755
    when: add_daily_stats

  - name: copy daily_stats
    template:
      src: templates/daily_stats.sh.j2
      dest: "{{ stats_dir }}/daily_stats.sh"
      mode: 0755
    when: add_daily_stats

  - name: Create secret.yml
    template:
      src: templates/secret.yml.j2
      dest: "{{ stats_dir }}/secret.yml"
      mode: 0600

  - name: Add env string to cron
    cron:
      name: SINFO_FORMAT
      env: yes
      job: "{{ sinfo_format }}"

  - name: Create cron job for galaxy_queue_size.py
    cron:
      name: "get_queue_size"
      minute: "*"
      job: "{{ virtualenv_dir }}/bin/python {{ stats_dir }}/get_queue_size.py{% if stats_instance is defined %} -i {{ stats_instance }}{% endif %}"
    when: add_utilisation_info or add_queue_info

  - name: Create cron job for daily stats
    cron:
      name: "daily_stats"
      minute: "40"
      hour: "10"
      job: "bash {{ stats_dir }}/daily_stats.sh"
    when: add_daily_stats

  - name: Create cron job for current stats
    cron:
      name: "current_stats"
      minute: "40"
      hour: "11"
      job: "bash {{ stats_dir }}/current_stats.sh"
    when: add_daily_stats

  - name: Copy monthly_stats_collector.py
    copy:
      src: files/monthly_stats_collector.py
      dest: "{{ stats_dir }}/monthly_stats_collector.py"
      mode: 0766
    when: add_monthly_stats
    