
auth_key_user: ubuntu

head_nodes: "{{ groups['pulsar_paw_head'] }}"
worker_nodes: "{{ groups['pulsar_paw_workers'] }}"

# SLURM
slurm_nodes:
    - name: pulsar-paw
      NodeAddr: "{{ hostvars['pulsar-paw']['internal_ip'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-paw-w1
      NodeAddr: "{{ hostvars['pulsar-paw-w1']['internal_ip'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-paw-w2
      NodeAddr: "{{ hostvars['pulsar-paw-w2']['internal_ip'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-paw-w3
      NodeAddr: "{{ hostvars['pulsar-paw-w3']['internal_ip'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-paw-w4
      NodeAddr: "{{ hostvars['pulsar-paw-w4']['internal_ip'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-paw-w5
      NodeAddr: "{{ hostvars['pulsar-paw-w5']['internal_ip'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "pulsar-paw-w1,pulsar-paw-w2,pulsar-paw-w3,pulsar-paw-w4,pulsar-paw-w5"
      Default: YES
      MaxTime: INFINITE
      State: UP

slurm_controller_host: pulsar-paw

slurm_munge_key: files/keys/munge.key
