---

- name: Ensure local repo directory exists
  file:
    path: /opt/deb
    state: directory

- name: add opt deb to sources list
  lineinfile:
    path: /etc/apt/sources.list.d/local.list
    line: deb [trusted=yes] file:/opt deb/
    create: true

- name: import module
  get_url:
    url: "{{ nginx_prebuilt_module_url }}"
    dest: /opt/deb

- name: Update the package manager to be aware of the dynamic module package
  shell: dpkg-scanpackages deb | gzip > deb/Packages.gz
  args:
    chdir: /opt

- name: install module
  apt:
    name: nginx-module-uploadmodule
    update_cache: true
  register: module_installed_result

- name: debug
  debug:
    msg: "{{ module_installed_result }}"

- name: Extract module path from install result
  set_fact:
    path_to_module: "{{ module_installed_result.stdout | regex_search(regexp,'\\1') }}"
  vars:
    regexp: 'load_module ([^\s;]*)'

- name: Add line to enable module in nginx conf
  lineinfile:
    insertbefore: 'events {'
    firstmatch: true
    path: /etc/nginx/nginx.conf
    line: 'load_module {{ path_to_module }};'
  when: path_to_module != ''
