attached_volumes:
  - device: /dev/vdZZZZZZ  # TODO: Find out
    path: /mnt
    fstype: ext4
    partition: 1

galaxy_job_dir: /mnt/tmp

nfs_exports:
  - "{{ galaxy_job_dir }} {{ hostvars['aarnet'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"