aarnet_galaxy_server_address: "{{ hostvars['aarnet']['internal_ip'] }}/32"

postgresql_flavor: pgdg
postgresql_version: 14

attached_volumes:
  - device: /dev/vdb
    path: /data
    partition: 1
    fstype: ext4

postgresql_conf:
  # Postgresql settings from: https://pgtune.leopard.in.ua/#/ - recommended by @natefoo.
  # Inout settings:
  #   DB Version: 12
  #   OS Type: linux
  #   DB Type: web
  #   Total Memory (RAM): 32 GB
  #   CPUs num: 8
  #   Connections num: 100
  #   Data Storage: san
  - max_connections: 200
  - listen_addresses: "'*'"   # Allow remote connections
  - data_directory: "'/data/production'"
  - shared_buffers: 8GB
  - effective_cache_size: 12GB
  - maintenance_work_mem : 2GB
  - checkpoint_completion_target: 0.7
  - wal_buffers: 16MB
  - default_statistics_target: 100
  - random_page_cost: 4
  - effective_io_concurrency: 2
  - work_mem: 32MB
  - min_wal_size: 1GB
  - max_wal_size: 4GB
  - max_worker_processes: 8
  - max_parallel_workers_per_gather: 4
  - max_parallel_workers: 8
  - max_parallel_maintenance_workers: 4
  - temp_buffers: 64MB
  # - log_filename: "'postgresql-%Y-%m-%d.log'"
  # - log_statement: all
  # - logging_collector: on  # altering this requires a restart



postgresql_pgdata: "/data/production"


postgresql_pg_hba_conf:
  - host all all "{{ aarnet_galaxy_server_address }}" md5 #The allowed connection to the database for the dev galaxy server.
  - host all all "{{ hostvars['aarnet']['ansible_ssh_host'] }}/32" md5
  - host all all "{{ hostvars['aarnet-backup']['internal_ip'] }}/32" md5 #The allowed connection to the database from the backup server.
  # - host replication postgres	"{{ hostvars['QLD-DR-db']['ansible_ssh_host'] }}/32" trust #connection from replication database
