attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
  - device: /dev/vdc
    path: /user-data-0
    fstype: ext4

galaxy_user_data_dir: /mnt/user-data
galaxy_test_user_data_dir: /user-data-0

nfs_exports:
  - "{{ galaxy_user_data_dir }} {{ hostvars['aarnet-user-nfs']['internal_ip'] }}(rw,async,no_root_squash,no_subtree_check)"
  - "{{ galaxy_test_user_data_dir }} {{ hostvars['aarnet-user-nfs']['internal_ip'] }}/24(rw,async,no_root_squash,no_subtree_check)"