dev_galaxy_server_address: "{{ hostvars['dev']['ansible_ssh_host'] }}/32"

postgresql_conf:
  - max_connections: 50       # Decrease connection limit
  - listen_addresses: "'*'"   # Allow remote connections

postgresql_pg_hba_conf:
  - host all all "{{ dev_galaxy_server_address }}" md5 #The allowed connection to the database for the dev galaxy server.

postgresql_objects_users:
  - name: galaxy
    password: "{{ galaxy_dev_db_user_password}}"
    db: galaxy
    priv: "ALL"
  - name: reader
    password: "{{ reader_dev_db_user_password }}"
    db: galaxy
    priv: "SELECT"
postgresql_objects_databases:
  - name: galaxy
    owner: galaxy

galaxy_dev_db_user_password: "{{ vault_dev_db_user_password }}"
