# Specific settings for galaxy dev application/web server

__galaxy_config:
  galaxy:
    brand: "Cat Dev"
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"  # cat-dev branch run db on application server

# NFS stuff
nfs_exports:
    - "{{ galaxy_root }}  *(rw,async,no_root_squash,no_subtree_check)"


galaxy_dev_db_user_password: e15ff41b834295f6
reader_dev_db_user_password: e15ff41b834295e2

# cat-dev branch include postgresql variables here
# PostgreSQL
postgresql_objects_users:
  - name: galaxy
    password: "{{ galaxy_dev_db_user_password}}"
    db: galaxy
    priv: "ALL"
  - name: reader
    password: "{{ reader_dev_db_user_password }}"
    db: galaxy
postgresql_objects_privileges:
  - database: galaxy
    roles: reader
    objs: ALL_IN_SCHEMA
    privs: SELECT
postgresql_objects_databases:
  - name: galaxy
    owner: galaxy
# end cat-dev branch insertion

# gxadmin
gxadmin_dir: "{{ galaxy_root }}/dev"
gxadmin_config_dir: "{{ galaxy_root }}/dev/gxadmin-config"

#Galaxy Job Conf
galaxy_jobconf:
    plugin_workers: 4
    handlers:
        count: "{{ galaxy_handler_count }}"
    plugins:
      - id: local
        load: galaxy.jobs.runners.local:LocalJobRunner
        workers: 4
      - id: slurm
        load: galaxy.jobs.runners.slurm:SlurmJobRunner
    default_destination: "slurm_dest"
    destinations:
      - id: local
        runner: local
      - id: dynamic_dtd
        runner: dynamic
        params:
          type: dtd
      - id: slurm_dest
        runner: slurm
        params:
            nativeSpecification: "--nodes=1 --ntasks=2 --ntasks-per-node=2 --mem=7760"
    tools:
      - id: upload1
        destination: slurm_dest
    limits:
      #General limits for user submission
      - type: anonymous_user_concurrent_jobs
        value: 1
      - type: registered_user_concurrent_jobs
        value: 10

# # variables for attaching mounted volume to application server
# galaxyserver_attached_volume_device: /dev/vdb
# galaxyserver_attached_volume_path: /mnt
# galaxyserver_attached_volume_fstype: ext4
