# Specific settings for galaxy dev application/web server

__galaxy_config:
  galaxy:
    brand: "Australia Dev"
    database_connection: "postgres://galaxy:{{ vault_dev_db_user_password }}@dev-db.usegalaxy.org.au:5432/galaxy"
    id_secret: "{{ vault_dev_id_secret }}"

# NFS stuff
nfs_exports:
    - "{{ galaxy_root }}  *(rw,async,no_root_squash,no_subtree_check)"

#Galaxy Job Conf
galaxy_jobconf:
    plugin_workers: 4
    handlers:
        count: "{{ galaxy_handler_count }}"
    plugins:
      - id: local
        load: galaxy.jobs.runners.local:LocalJobRunner
        workers: 4
      - id: slurm
        load: galaxy.jobs.runners.slurm:SlurmJobRunner
      - id: pulsar_au_01
        load: galaxy.jobs.runners.pulsar:PulsarMQJobRunner
        params:
            amqp_url: "pyamqp://galaxy_au:{{ vault_rabbitmq_password_galaxy_au_dev }}@dev-queue.usegalaxy.org.au:5671//pulsar/galaxy_au?ssl=1"
            galaxy_url: "https://dev.usegalaxy.org.au"
            manager: _default_
            amqp_acknowledge: True
            amqp_ack_republish_time: 300
            amqp_consumer_timeout: 2.0
            amqp_publish_retry: True
            amqp_publish_retry_max_retries: 60
    default_destination: "slurm_dest"
    destinations:
      - id: local
        runner: local
      - id: dynamic_dtd
        runner: dynamic
        params:
          type: dtd
      - id: slurm_dest
        runner: slurm
        params:
            nativeSpecification: "--nodes=1 --ntasks=2 --ntasks-per-node=2 --mem=7760"
      - id: pulsar_destination
        runner: pulsar_au_01
        params:
              jobs_directory: /mnt/pulsar/files/staging
              transport: curl
              remote_metadata: "false"
              default_file_action: remote_transfer
              dependency_resolution: remote
              rewrite_parameters: "true"
              persistence_directory: /mnt/pulsar/files/persisted_data
              submit_native_specification: "--nodes=1 --ntasks=2 --ntasks-per-node=2"
    tools:
      - id: upload1
        destination: slurm_dest
      - id: toolshed.g2.bx.psu.edu/repos/iuc/fasta_stats/fasta-stats/1.0.1
        destination: pulsar_destination
      - id: toolshed.g2.bx.psu.edu/repos/devteam/bwa/bwa_mem/0.7.17.1
        destination: pulsar_destination
    limits:
      #General limits for user submission
      - type: anonymous_user_concurrent_jobs
        value: 1
      - type: registered_user_concurrent_jobs
        value: 10

# variables for attaching mounted volume to application server
galaxyserver_attached_volume_device: /dev/vdb
galaxyserver_attached_volume_path: /mnt
galaxyserver_attached_volume_fstype: ext4

# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs

# slurm head node 
head_nodes: "{{ groups['dev_slurm_head'] }}"