attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
    partition: 1

nfs_job_dir: /mnt/tmp

nfs_exports:
  - "{{ nfs_job_dir }} {{ hostvars['galaxy'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"

extra_keys:
  - id: ubuntu_maintenance_key
    type: public
    from: "{{ hostvars['galaxy']['internal_ip'] }}"
