attached_volumes:
  - device: /dev/vdc
    path: /mnt
    fstype: ext4

galaxy_user_data_dir: /mnt/user-data

nfs_exports:
  - "{{ galaxy_user_data_dir }} 192.168.0.0/24(rw,async,no_root_squash,no_subtree_check)"