attached_volumes:
  - device: /dev/vdc
    path: /mnt
    fstype: ext4

galaxy_nfs_app_dir: /mnt/ghost-galaxy-app
galaxy_nfs_tools_dir: /mnt/tools-indices

nfs_exports:
  - "{{ galaxy_nfs_app_dir }} 192.168.0.0/24(rw,async,no_root_squash,no_subtree_check)"
  - "{{ galaxy_nfs_tools_dir }} 192.168.0.0/24(rw,async,no_root_squash,no_subtree_check)"