
auth_key_user: ubuntu

head_nodes: "{{ groups['pulsar_mel2_head'] }}"
worker_nodes: "{{ groups['pulsar_mel2_workers'] }}"

# SLURM
slurm_nodes:
    - name: pulsar-mel2
      NodeAddr: "{{ hostvars['pulsar-mel2']['ansible_ssh_host'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-mel2-w1
      NodeAddr: "{{ hostvars['pulsar-mel2-w1']['ansible_ssh_host'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-mel2-w2
      NodeAddr: "{{ hostvars['pulsar-mel2-w2']['ansible_ssh_host'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-mel2-w3
      NodeAddr: "{{ hostvars['pulsar-mel2-w3']['ansible_ssh_host'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-mel2-w4
      NodeAddr: "{{ hostvars['pulsar-mel2-w4']['ansible_ssh_host'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-mel2-w5
      NodeAddr: "{{ hostvars['pulsar-mel2-w5']['ansible_ssh_host'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-mel2-w6
      NodeAddr: "{{ hostvars['pulsar-mel2-w6']['ansible_ssh_host'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN
    - name: pulsar-mel2-w7
      NodeAddr: "{{ hostvars['pulsar-mel2-w7']['ansible_ssh_host'] }}"
      CPUs: 8
      RealMemory: 32000
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "pulsar-mel2-w1,pulsar-mel2-w2,pulsar-mel2-w3,pulsar-mel2-w4,pulsar-mel2-w5,pulsar-mel2-w6,pulsar-mel2-w7"
      Default: YES
      MaxTime: INFINITE
      State: UP

slurm_controller_host: pulsar-mel2

slurm_munge_key: files/keys/munge.key
