auth_key_user: ubuntu

head_nodes: "{{ groups['pulsar_QLD_queue'] }}"
worker_nodes: "{{ groups['pulsar_QLD_workers'] }}"
galaxy_nodes: "{{ groups['pulsar_QLD_head'] }}"

# SLURM
slurm_nodes:
  - name: pulsar-QLD
    NodeAddr: "{{ hostvars['pulsar-QLD']['ansible_ssh_host'] }}"
    CPUs: 8
    RealMemory: 64000
    State: UNKNOWN
  - name: pulsar-QLD-w0
    NodeAddr: "{{ hostvars['pulsar-QLD-w0']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64000
    State: UNKNOWN
  - name: pulsar-QLD-w1
    NodeAddr: "{{ hostvars['pulsar-QLD-w1']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64000
    State: UNKNOWN
  - name: pulsar-QLD-w2
    NodeAddr: "{{ hostvars['pulsar-QLD-w2']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64000
    State: UNKNOWN
  - name: pulsar-QLD-w3
    NodeAddr: "{{ hostvars['pulsar-QLD-w3']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64000
    State: UNKNOWN
  - name: pulsar-QLD-w4
    NodeAddr: "{{ hostvars['pulsar-QLD-w4']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64000
    State: UNKNOWN
  - name: pulsar-QLD-w5
    NodeAddr: "{{ hostvars['pulsar-QLD-w5']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64000
    State: UNKNOWN
  - name: pulsar-QLD-w6
    NodeAddr: "{{ hostvars['pulsar-QLD-w6']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64000
    State: UNKNOWN

slurm_partitions:
  - name: main
    nodes: "pulsar-QLD-w0,pulsar-QLD-w1,pulsar-QLD-w2,pulsar-QLD-w3,pulsar-QLD-w4,pulsar-QLD-w5,pulsar-QLD-w6"
    Default: YES
    MaxTime: INFINITE
    State: UP

slurm_controller_host: pulsar-QLD-queue

slurm_munge_key: files/keys/munge.key
