name: Ansible Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # number of commits to fetch. 0 indicates all history for all branches and tags
    # Set up python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    # Install python dependencies for check_files script
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 ansible-lint==5.0.7
    - name: Lint playbooks
      run: ansible-lint -c .ci/.ansible-lint *playbook.yml